window.ZENIX_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "electronics", label: "Electronics" },
  { id: "fashion", label: "Fashion" },
  { id: "furniture", label: "Furniture" },
  { id: "beauty", label: "Beauty" },
  { id: "home", label: "Home" }
];

window.ZENIX_PRODUCTS = [
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "electronics",
    price: 149999,
    oldPrice: 159999,
    rating: 4.9,
    reviews: 128,
    stock: 18,
    badge: "Best seller",
    image: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A premium titanium smartphone with a fast chip, crisp display, and pro-grade camera system.",
    features: ["A17 class performance", "Pro camera system", "All-day battery", "Titanium finish"]
  },
  {
    id: "samsung-s24-ultra",
    name: "Samsung S24 Ultra",
    category: "electronics",
    price: 134999,
    oldPrice: 144999,
    rating: 4.8,
    reviews: 96,
    stock: 14,
    badge: "New",
    image: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A large-screen flagship built for photography, productivity, and smooth everyday performance.",
    features: ["High-resolution camera", "Integrated stylus support", "Bright AMOLED display", "Fast charging"]
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    category: "electronics",
    price: 69999,
    oldPrice: 74999,
    rating: 4.7,
    reviews: 82,
    stock: 24,
    badge: "Value pick",
    image: "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A fast, polished smartphone with strong cameras, smooth scrolling, and reliable battery life.",
    features: ["Flagship processor", "Hasselblad-tuned camera", "120Hz display", "Large battery"]
  },
  {
    id: "gaming-laptop",
    name: "Gaming Laptop",
    category: "electronics",
    price: 89999,
    oldPrice: 99999,
    rating: 4.6,
    reviews: 74,
    stock: 10,
    badge: "Hot deal",
    image: "https://images.pexels.com/photos/538064/pexels-photo-538064.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A performance laptop tuned for games, streaming, and demanding creative workloads.",
    features: ["Dedicated graphics", "High refresh display", "Backlit keyboard", "Thermal cooling"]
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    category: "electronics",
    price: 114999,
    oldPrice: 119999,
    rating: 4.9,
    reviews: 145,
    stock: 12,
    badge: "Featured",
    image: "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=900",
    desc: "A thin, silent laptop with excellent battery life and power for everyday creative work.",
    features: ["M3 performance", "Fanless design", "Lightweight body", "Long battery life"]
  },
  {
    id: "ipad-pro",
    name: "iPad Pro",
    category: "electronics",
    price: 79999,
    oldPrice: 84999,
    rating: 4.7,
    reviews: 61,
    stock: 16,
    badge: "Creative",
    image: "https://images.pexels.com/photos/1008217/pexels-photo-1008217.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A brilliant tablet for sketching, entertainment, notes, and portable productivity.",
    features: ["Liquid Retina display", "Pencil support", "Lightweight build", "Powerful apps"]
  },
  {
    id: "wireless-headphones",
    name: "Wireless Headphones",
    category: "electronics",
    price: 3499,
    oldPrice: 4999,
    rating: 4.5,
    reviews: 212,
    stock: 40,
    badge: "Under 5000",
    image: "https://images.pexels.com/photos/159853/headphones-headset-audio-equipment-159853.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "Comfortable wireless headphones with rich sound and reliable noise isolation.",
    features: ["Wireless audio", "Soft ear cushions", "Noise isolation", "Foldable design"]
  },
  {
    id: "bluetooth-speaker",
    name: "Bluetooth Speaker",
    category: "electronics",
    price: 4999,
    oldPrice: 6499,
    rating: 4.4,
    reviews: 89,
    stock: 35,
    badge: "Portable",
    image: "https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A compact speaker with deep bass, clean vocals, and travel-friendly battery life.",
    features: ["Portable body", "Deep bass", "Bluetooth pairing", "Splash resistant"]
  },
  {
    id: "smartwatch",
    name: "Smartwatch",
    category: "electronics",
    price: 12999,
    oldPrice: 14999,
    rating: 4.3,
    reviews: 118,
    stock: 28,
    badge: "Fitness",
    image: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A fitness-focused smartwatch with health tracking, notifications, and clean styling.",
    features: ["Heart-rate tracking", "Workout modes", "Notifications", "Water resistant"]
  },
  {
    id: "men-shirt",
    name: "Premium Cotton Shirt",
    category: "fashion",
    price: 1999,
    oldPrice: 2499,
    rating: 4.5,
    reviews: 57,
    stock: 42,
    badge: "Daily wear",
    image: "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A breathable cotton shirt with a clean fit for office days and evening plans.",
    features: ["Soft cotton", "Tailored fit", "Easy care", "Formal styling"]
  },
  {
    id: "women-dress",
    name: "Elegant Midi Dress",
    category: "fashion",
    price: 2999,
    oldPrice: 3899,
    rating: 4.6,
    reviews: 64,
    stock: 33,
    badge: "Limited",
    image: "https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A refined midi dress with a graceful silhouette for dinners, events, and weekends.",
    features: ["Soft fabric", "Modern cut", "Event-ready", "Comfort lining"]
  },
  {
    id: "running-shoes",
    name: "Running Shoes",
    category: "fashion",
    price: 4499,
    oldPrice: 5999,
    rating: 4.7,
    reviews: 134,
    stock: 38,
    badge: "Sport",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "Lightweight running shoes with cushioned support for training and everyday movement.",
    features: ["Cushioned sole", "Breathable mesh", "Grippy outsole", "Lightweight build"]
  },
  {
    id: "sofa-set",
    name: "Modern Sofa Set",
    category: "furniture",
    price: 55999,
    oldPrice: 64999,
    rating: 4.6,
    reviews: 39,
    stock: 7,
    badge: "Home upgrade",
    image: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A comfortable sofa set with clean lines and generous seating for modern homes.",
    features: ["Solid frame", "Plush cushions", "Durable upholstery", "Easy maintenance"]
  },
  {
    id: "accent-chair",
    name: "Accent Lounge Chair",
    category: "furniture",
    price: 18999,
    oldPrice: 21999,
    rating: 4.4,
    reviews: 28,
    stock: 11,
    badge: "Editor pick",
    image: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A sculpted lounge chair that adds warmth and comfort to reading corners and living rooms.",
    features: ["Ergonomic seat", "Solid legs", "Soft upholstery", "Compact footprint"]
  },
  {
    id: "makeup-kit",
    name: "Professional Makeup Kit",
    category: "beauty",
    price: 3499,
    oldPrice: 4699,
    rating: 4.5,
    reviews: 93,
    stock: 31,
    badge: "Beauty",
    image: "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A curated makeup kit with versatile shades for daily looks and special occasions.",
    features: ["Curated shades", "Travel case", "Blendable textures", "Long wear"]
  },
  {
    id: "ceramic-dinner-set",
    name: "Ceramic Dinner Set",
    category: "home",
    price: 5999,
    oldPrice: 7999,
    rating: 4.6,
    reviews: 47,
    stock: 26,
    badge: "Dining",
    image: "https://images.pexels.com/photos/4871118/pexels-photo-4871118.jpeg?auto=compress&cs=tinysrgb&w=900",
    desc: "A refined ceramic dinner set for everyday meals, hosting, and thoughtful gifting.",
    features: ["Microwave safe", "Dishwasher safe", "Modern glaze", "Service for four"]
  }
];

window.ZENIX_COUPONS = {
  SAVE10: { type: "percent", value: 10, min: 1000, label: "10% off" },
  SAVE20: { type: "percent", value: 20, min: 25000, label: "20% off" },
  FLAT500: { type: "flat", value: 500, min: 5000, label: "INR 500 off" }
};
